### ISSUE TITLE
DataFrame read and write ops in check_dicom_status.py

### ISSUE THREAD

**Issue by nikhil153** [nipoppy/nipoppy#167]
Currently seeing one error from `load_manifest` and a warning while populating status_df. 
---
Error: this can be circumvented if we read the CSV directly with `pd.read_csv` 
```(nipoppy) nikhil@ducky:/data/origami/nikhil/my_repos/nipoppy-qpn/nipoppy/workflow/dicom_org$ python check_dicom_status.py --global_config /data/origami/nikhil/datasets/sandbox/qpn/proc/global_configs.json --regenerate
Traceback (most recent call last):
  File "/data/origami/nikhil/my_repos/nipoppy-qpn/nipoppy/workflow/dicom_org/check_dicom_status.py", line 252, in <module>
    run(global_config_file, regenerate=regenerate, empty=empty)
  File "/data/origami/nikhil/my_repos/nipoppy-qpn/nipoppy/workflow/dicom_org/check_dicom_status.py", line 60, in run
    df_manifest = load_manifest(fpath_manifest)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/origami/nikhil/my_repos/nipoppy-qpn/nipoppy/workflow/utils.py", line 85, in load_manifest
    return pd.read_csv(
           ^^^^^^^^^^^^
  File "/data/origami/nikhil/my_envs/nipoppy/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/origami/nikhil/my_envs/nipoppy/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/data/origami/nikhil/my_envs/nipoppy/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/origami/nikhil/my_envs/nipoppy/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 920, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 1044, in pandas._libs.parsers.TextReader._convert_column_data
  File "parsers.pyx", line 2113, in pandas._libs.parsers._apply_converter
  File "/data/origami/nikhil/my_envs/nipoppy/lib/python3.11/site-packages/pandas/core/computation/eval.py", line 303, in eval
    _check_expression(expr)
  File "/data/origami/nikhil/my_envs/nipoppy/lib/python3.11/site-packages/pandas/core/computation/eval.py", line 120, in _check_expression
    raise ValueError("expr cannot be an empty string")
ValueError: expr cannot be an empty string
```
@michellewang  - I kinda understand where this is coming from but wanted to check with you since pandas converters to read lists from CSVs is a bit messy.

--- 
Warning: 
``` 
/data/origami/nikhil/my_repos/nipoppy-qpn/nipoppy/workflow/dicom_org/check_dicom_status.py:224: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. 
```
This is because of status Series is initialized as numpy float on the line:
```  
status = pd.Series(np.nan, index=df.index)
```
And can be fixed by setting it to `False` 
```
status = pd.Series(False, index=df.index)
```

**Comment by michellewang** [comment]
@nikhil153 is this for the `datatype` column in the manifest? It needs to be an empty list if no datatypes are available. If you just use `pd.read_csv` I don’t think you get a list (think it gives a string)?

**Comment by nikhil153** [comment]
@michellewang - oh right, we did talk about that. But let's put that as a check in the function with more informative error message than Panda's `ValueError`. It won't be trivial for other users to create manifest with empty [] for `datatype`.

**Comment by michellewang** [comment]
Closing as this is related to the old (script-based) version of Nipoppy
